experiment_name: "simple_rag"

llm:
  provider: "bedrock" 
  model_spec:
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"
    model_kwargs: 
      max_tokens: 4096
      temperature: 0
      top_p: 0
      stop_sequences: ["\n\nHuman"]
  prompt:
    system_message: Act like a Machine Learning Teacher
    user_message: Ask a question or provide a prompt

embedder:
  model_id: "amazon.titan-embed-text-v2:0"
  model_kwargs: 
    dimensions: 512
    normalize: True

retriever:
  search_type: "similarity"
  retriever_kwargs:
    k: 5

chunker:
  chunk_size: 1500
  chunk_overlap: 100

data:
  path: "./data/raw/"

vector_store:
  path: "./data/database_1500_100"